//CRUD de USER

###
GET http://localhost:4000/api/users
###
POST http://localhost:4000/api/users
content-Type: application/json

{
    "userName": "Yun",
    "email": "yun@gmail.com",
    "password": "yun5678"
} 

###
DELETE http://localhost:4000/api/users/:id
###
PUT http://localhost:4000/api/users/6091d6732d3a564454063110
content-Type: application/json

{
    "userName": "Jonatan"

} 
###
GET http://localhost:4000/api/users/608dc69df661910fb86c8f3d

###
POST http://localhost:4000/api/users/logIn
content-Type: application/json

{
    "email": "yun@gmail.com",
    "password": "yun5678"

}

###
PUT http://localhost:4000/api/users/forgotPassword
content-Type: application/json

{
    "email": "hector.fernandez.granja@estudiantat.upc.edu"
}

###
PUT http://localhost:4000/api/users/resetPassword
content-Type: application/json

{
    "resetLink": "",
    "newPass": "3nw20",
    "confNewPass": "3nw20"
}

###
GET http://localhost:4000/api/users/localhost:4000/api/lots/getByUser/60a8379570e909276c35b7c0

//CRUD de LOT

###
GET http://localhost:4000/api/lots

###
POST http://localhost:4000/api/lots
content-Type: application/json

{
    "name": "Queso",
    "dimensions": "60x30x15",
    "weight": 60,
    "qty": 40,
    "price": 1,
    "isFragile": true,
    "info": "Cabra",
    "minimumQty": 40,
    "businessItem": "60a69ae76196f9208c4f8a86",
    "userItem":"60a69ae76196f9208c4f8a86"
} 

###
DELETE http://localhost:4000/api/lots/6092eb5193496c0ac44f67df

###
PUT http://localhost:4000/api/lots/60a161814c1c6a41446e1034
content-Type: application/json

{
    "name": "Leche",
    "dimensions": "60x30x15",
    "weight": 60,
    "userItem": "6091cbdf81612f2a801c068f",
    "qty": 40,
    "price": 150,
    "isFragile": true,
    "info": "HA CAMBIADO OU YEAH",
    "minimumQty": 40,
    "businessItem": "6091cbdf81612f2a801c068f"
} 

###
GET http://localhost:4000/api/lots/60a69ae76196f9208c4f8a86

//Buscamos LOT por nombre pasado por parámetro

###
GET http://localhost:4000/api/lots/get/Leche

//CRUD DE DELIVERY

### 
GET http://localhost:4000/api/delivery/
###
POST http://localhost:4000/api/delivery/609c29591c34f216f043c43d/deliveries
###
POST  http://localhost:4000/api/delivery/609c29591c34f216f043c43d/readydeliveries
###
POST  http://localhost:4000/api/delivery/readydelivery
content-Type: application/json 

{
    "id": "60a258caa9103b2548a13ac4"
}
###
POST http://localhost:4000/api/delivery/
content-Type: application/json

{
    "lots":"609c49134f2a8c39548b977b",
    "lotItem": "609c49134f2a8c39548b977b",
    "originLocation": "3.4379º,-2.1179º",
    "destinationLocation": "3.4279º,-2.179º",
    "destinationItem": "6091d6782d3a564454063112",
    "deliveryDate": "13/09/2017",
    "isPicked": true,
    "isDelivered": false,
    "isReady": true,
    "businessItem":"60993b2b9ee40b10046c59bb",
    "isAssigned": true,
    "userItem": "609c29591c34f216f043c43d",
    "description": "Picar al 1o 1a"
} 
###
DELETE http://localhost:4000/api/delivery/609c4a5f4f2a8c39548b977c
###
PUT http://localhost:4000/api/delivery/609c29951c34f216f043c43e
content-Type: application/json 

{
    "lotItem": "6091cfbc57de44327c1eb88f""609c49134f2a8c39548b977b",
    "originLocation": "3.4379º,-2.1179º",
    "destinationLocation": "3.4279º,-2.179º",
    "destinationItem": "6091d6732d3a564454063110",
    "deliveryDate": "13/09/2017",
    "isPicked": true,
    "isDelivered": true,
    "businessItem":"6091d6762d3a564454063111",
    "isAssigned": true,
    "userItem": "6091d6782d3a564454063112",
    "description": "Ahora pica al 4o que el del 1o no viene"
} 
###
GET http://localhost:4000/api/delivery/609c54bda34787271456871e