//CRUD de USER

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/getNumByRole/Company

###
GET http://localhost:3000/api/users/60c4f100aaaa0a33e4e27ebd

###
PUT http://localhost:3000/api/users/60a84313cd1c2549f80c1c02
content-Type: application/json

{
    "email": "etc@etc.com"
} 

###
POST http://localhost:3000/api/users
content-Type: application/json

{
    "userName": "hectorprova",
    "email": "hector.fernandez.granja@estudiantat.upc.edu",
    "password": "12345"
} 

###
DELETE http://localhost:3000/api/users/:id

###
PUT http://localhost:3000/api/users/60be61ae74ee9a25041a649e
content-Type: application/json

{
    "role": "User"

} 

###
GET http://localhost:3000/api/users/608dc69df661910fb86c8f3d

###
POST http://localhost:3000/api/users/logIn
content-Type: application/json

{
    "email": "hector.fernandez.granja@estudiantat.upc.edu",
    "password": "hola"
}

###
POST http://localhost:3000/api/users/forgotPassword
content-Type: application/json

{
    "email": "hector.fernandez.granja@estudiantat.upc.edu"
}

###
POST http://localhost:3000/api/users/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGE4NDMxM2NkMWMyNTQ5ZjgwYzFjMDIiLCJpYXQiOjE2MjM1MTI2NTQsImV4cCI6MTYyMzUxMjk1NH0.hKU54Kpr8_e1TfsJYAB4-LOIrZrt10ICAlGzisE9X30
content-Type: application/json

{
    "newPass": "nuevo1",
    "confNewPass": "nuevo1"
}





//HTTP OF LOTS-LOTS-LOTS-LOTS



###
GET http://localhost:3000/api/lots/All
###
GET http://localhost:3000/api/lots/getByUser/60b684372ffee403ecae5fa2

###
GET http://localhost:3000/api/lots/getByUser/60a8379570e909276c35b7c0

###
GET http://localhost:3000/api/lots/getNumAll

###
GET http://localhost:3000/api/lots/getSortLotsByAscPrice/60a8379570e909276c35b7c0

###
GET http://localhost:3000/api/lots/getSortLotsByAscQty/60a8379570e909276c35b7c0

###
POST http://localhost:3000/api/lots
content-Type: application/json

{
    "name": "otro5",
    "dimensions": "60x30x15",
    "weight": 60,
    "qty": 40,
    "price": 12,
    "isFragile": true,
    "info": "otro5",
    "minimumQty": 40,
    "businessItem": "60b0b73999e1c70758c73b7b",
    "userItem":"60a8379570e909276c35b7c0"
} 

###
DELETE http://localhost:3000/api/lots/60b22a24192afd215c5fe505

###
PUT http://localhost:3000/api/lots/60a161814c1c6a41446e1034
content-Type: application/json

{
    "name": "Leche",
    "dimensions": "60x30x15",
    "weight": 60,
    "userItem": "6091cbdf81612f2a801c068f",
    "qty": 40,
    "price": 150,
    "isFragile": true,
    "info": "HA CAMBIADO OU YEAH",
    "minimumQty": 40,
    "businessItem": "60aeaf411ffb7307940ae113"
} 

###
GET http://localhost:3000/api/lots/60a69ae76196f9208c4f8a86

//Buscamos LOT por nombre pasado por parámetro

###
GET http://localhost:3000/api/lots/get/Leche

//CRUD DE DELIVERY

### 
GET http://localhost:3000/api/delivery/

###
GET http://localhost:3000/api/delivery/getNumAll

###
GET http://localhost:3000/api/delivery/60b0b73999e1c70758c73b7b/deliveries
###
GET   http://localhost:3000/api/delivery/60b0b73999e1c70758c73b7b/readydeliveries
###
PUT   http://localhost:3000/api/delivery/readydelivery/60b0e35fb1cdf634acb5ae8b

###
POST http://localhost:3000/api/delivery/
content-Type: application/json

{
    "lotItem": "60ca074d33952b28c0146962",
    "userItem": "60cb47fe19082604d0140b06"
    "businessItem": 

} 
###
DELETE http://localhost:3000/api/delivery/609c4a5f4f2a8c39548b977c
###
PUT http://localhost:3000/api/delivery/609c29951c34f216f043c43e
content-Type: application/json 

{
    "lotItem": "6091cfbc57de44327c1eb88f",
    "originLocation": "3.4379º,-2.1179º",
    "destinationLocation": "3.4279º,-2.179º",
    "destinationItem": "6091d6732d3a564454063110",
    "deliveryDate": "13/09/2017",
    "isPicked": true,
    "isDelivered": true,
    "businessItem":"6091d6762d3a564454063111",
    "isAssigned": true,
    "userItem": "6091d6782d3a564454063112",
    "description": "Ahora pica al 4o que el del 1o no viene"
} 
###
GET http://localhost:3000/api/delivery/609c54bda34787271456871e